# fetch ssh host key and store the key into the local known_hosts file
---
- name: Ensure ssh host key(s) are cached.
  delegate_to: localhost
  run_once: true
  become: false
  known_hosts:
    path: "{{ bootstrap_ssh_key_hosts_file | d(omit) }}"
    host: "{{ item }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t ' + bootstrap_ssh_key_type + ' -p ' + (hostvars[item]['ansible_ssh_port'] | default('22')) + ' ' + item) }}"
    state: present
    hash_host: "{{ bootstrap_ssh_key_hash_hostname }}"
  with_items: "{{ ansible_play_batch }}"
